[build-system]
requires = ["setuptools>=61.0", "wheel"]
build_backend = "setuptools.backends.legacy:build"

[project]
name = "tissu"
version = "1.0.0"
description = "A cloth simulation sdk for python"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
	"mypy",
	"tqdm",
	"numpy",
	"pytest"
]
authors = [{ name = "Evan Miranda"}]
license = { text = "Apache-2.0"}

[tool.setuptools.packages.find]
where = ["python"]

[tool.setuptools.package-data]
tissu = ["*.so", "*.pyd", "*.pyi", "shaders/*.vert", "shaders/*.frag"]