[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "pytissu"
version = "1.0.2"
description = "A cloth simulation SDK for Python"
readme = "README.md"
requires-python = ">=3.12"
license = "Apache-2.0"
authors = [{ name = "Evan Miranda" }]
keywords = ["cloth", "simulation", "physics", "3d"]

dependencies = [
    "numpy",
    "tqdm",
    "matplotlib",
    "imageio"
]

classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "Intended Audience :: Science/Research",
    "Natural Language :: English",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Topic :: Artistic Software",
    "Topic :: Multimedia :: Graphics :: 3D Modeling",
    "Topic :: Scientific/Engineering",
]

[project.optional-dependencies]
dev = ["mypy", "pytest"]

[project.urls]
Homepage = "https://github.com/evanrock520-ciencias/Tissu"
Repository = "https://github.com/evanrock520-ciencias/Tissu.git"
Issues = "https://github.com/evanrock520-ciencias/Tissu/issues"

[tool.setuptools.packages.find]
where = ["python"]

[tool.setuptools]
zip-safe = false

[tool.setuptools.package-data]
tissu = ["*.so", "*.pyd", "*.pyi", "shaders/*.vert", "shaders/*.frag"]

[tool.ruff]
line-length = 80
target-version = "py312"

[tool.ruff.lint]
select = [
    "E",
    "W",
    "F",
    "I",
    "B",
    "C4",
    "UP",
    "N",
    "SIM"
]
ignore = []

[tool.ruff.format]
quote-style = "double"
indent-style = "space"