import numpy
from typing import ClassVar, overload

class AeroFace:
    a: int
    b: int
    c: int
    def __init__(self, a: int, b: int, c: int) -> None: ...

class AerodynamicForce(Force):
    def __init__(self, arg0: list[AeroFace], arg1: numpy.ndarray[numpy.float64[3, 1]], arg2: float) -> None: ...

class AlembicExporter:
    def __init__(self) -> None: ...
    def close(self) -> None: ...
    def open(self, path: str, names: list[str], global_positions: numpy.ndarray[numpy.float64], global_indices: list, particle_indices: list) -> bool: ...
    def write_frame(self, global_positions: numpy.ndarray[numpy.float64], time: float) -> None: ...

class Application:
    def __init__(self) -> None: ...
    def get_renderer(self) -> Renderer: ...
    def init(self, width: int, height: int, title: str, shader_path: str) -> bool: ...
    def run(self) -> None: ...
    def set_aero_force(self, arg0: AerodynamicForce) -> None: ...
    def set_cloth(self, arg0: Cloth) -> None: ...
    def set_mesh(self, mesh: ClothMesh) -> None: ...
    def set_solver(self, solver: Solver) -> None: ...
    def set_world(self, arg0: World) -> None: ...
    def shutdown(self) -> None: ...
    def sync_visual_topology(self) -> None: ...

class BendingConstraint(Constraint):
    def __init__(self, idA: int, idB: int, idC: int, idD: int, restAngle: float, compliance: float) -> None: ...

class CapsuleCollider(Collider):
    def __init__(self, radius: float, start: numpy.ndarray[numpy.float64[3, 1]], end: numpy.ndarray[numpy.float64[3, 1]], friction: float) -> None: ...

class Cloth:
    def __init__(self, name: str, material: ClothMaterial) -> None: ...
    def get_aerofaces(self) -> list[AeroFace]: ...
    def get_material(self) -> ClothMaterial: ...
    def get_name(self) -> str: ...
    def get_particle_id(self, row: int, col: int) -> int: ...
    def get_particle_indices(self) -> list[int]: ...
    def get_pin(self) -> Pin: ...
    def get_rest_volume(self) -> float: ...
    def get_triangles(self) -> list[int]: ...
    def get_triangles_native(self) -> list[Triangle]: ...
    def is_closed(self) -> bool: ...
    def set_material(self, arg0: ClothMaterial) -> None: ...
    def set_pin(self, arg0: Pin) -> None: ...
    def set_rest_volume(self, arg0: float) -> None: ...

class ClothMaterial:
    bending_compliance: float
    density: float
    shear_compliance: float
    structural_compliance: float
    def __init__(self, density: float, structural: float, shear: float, bending: float) -> None: ...

class ClothMesh:
    def __init__(self) -> None: ...
    def build_from_mesh(self, positions: list[numpy.ndarray[numpy.float64[3, 1]]], indices: list[int], out_cloth, solver: Solver, mesh_path: str, translation: numpy.ndarray[numpy.float64[3, 1]] = ..., rotation: numpy.ndarray[numpy.float64[4, 1]] = ...) -> None: ...
    def init_grid(self, rows: int, cols: int, spacing: float, out_cloth, solver: Solver, translation: numpy.ndarray[numpy.float64[3, 1]] = ..., rotation: numpy.ndarray[numpy.float64[4, 1]] = ...) -> None: ...

class Collider:
    def __init__(self, *args, **kwargs) -> None: ...
    def get_friction(self) -> float: ...
    def set_friction(self, arg0: float) -> None: ...

class ColliderInfo:
    def __init__(self, *args, **kwargs) -> None: ...
    @property
    def summary(self) -> str: ...
    @property
    def type(self) -> str: ...

class ConfigLoader:
    def __init__(self, *args, **kwargs) -> None: ...
    @staticmethod
    def load_material(arg0: str, arg1: ClothMaterial) -> None: ...
    @staticmethod
    def load_physics(arg0: str, arg1: Solver, arg2: World) -> None: ...
    @staticmethod
    def save_material(arg0: str, arg1: ClothMaterial, arg2: str) -> None: ...
    @staticmethod
    def save_physics(arg0: str, arg1: Solver, arg2: World, arg3: str) -> None: ...

class Constraint:
    def __init__(self, *args, **kwargs) -> None: ...
    def reset_lambda(self) -> None: ...

class DistanceConstraint(Constraint):
    def __init__(self, idA: int, idB: int, restLength: float, compliance: float) -> None: ...

class FabricInfo:
    def __init__(self, *args, **kwargs) -> None: ...
    @property
    def cols(self) -> int: ...
    @property
    def material(self) -> str: ...
    @property
    def name(self) -> str: ...
    @property
    def pin_mode(self) -> str: ...
    @property
    def rows(self) -> int: ...
    @property
    def source(self) -> str: ...
    @property
    def spacing(self) -> float: ...
    @property
    def type(self) -> str: ...

class Force:
    def __init__(self, *args, **kwargs) -> None: ...

class GravityForce(Force):
    def __init__(self, arg0: numpy.ndarray[numpy.float64[3, 1]]) -> None: ...
    def get_gravity(self) -> numpy.ndarray[numpy.float64[3, 1]]: ...
    def set_gravity(self, arg0: numpy.ndarray[numpy.float64[3, 1]]) -> None: ...

class Logger:
    def __init__(self, *args, **kwargs) -> None: ...
    @staticmethod
    def error(message: str) -> None: ...
    @staticmethod
    def info(message: str) -> None: ...
    @staticmethod
    def warn(message: str) -> None: ...

class MeshCollider(Collider):
    @overload
    def __init__(self, mesh_path: str, friction: float) -> None: ...
    @overload
    def __init__(self, vertices: list[numpy.ndarray[numpy.float64[3, 1]]], triangles, friction: float) -> None: ...
    def get_mesh_path(self) -> str: ...

class OBJExporter:
    def __init__(self) -> None: ...
    @staticmethod
    def export_obj(filename: str, cloth: Cloth, solver: Solver) -> None: ...

class OBJLoader:
    def __init__(self, *args, **kwargs) -> None: ...
    @staticmethod
    def load(arg0: str) -> tuple[bool, list[numpy.ndarray[numpy.float64[3, 1]]], list[int]]: ...

class Particle:
    def __init__(self, initial_pos: numpy.ndarray[numpy.float64[3, 1]]) -> None: ...
    def add_force(self, arg0: numpy.ndarray[numpy.float64[3, 1]]) -> None: ...
    def get_inverse_mass(self) -> float: ...
    def get_old_position(self) -> numpy.ndarray[numpy.float64[3, 1]]: ...
    def get_position(self) -> numpy.ndarray[numpy.float64[3, 1]]: ...
    def get_velocity(self, arg0: float) -> numpy.ndarray[numpy.float64[3, 1]]: ...
    def integrate(self, arg0: float) -> None: ...
    def set_inverse_mass(self, arg0: float) -> None: ...
    def set_old_position(self, arg0: numpy.ndarray[numpy.float64[3, 1]]) -> None: ...
    def set_position(self, arg0: numpy.ndarray[numpy.float64[3, 1]]) -> None: ...

class Pin:
    def __init__(self, pin_mode: PinMode, compliance: float, threshold: float) -> None: ...
    def get_compliance(self) -> float: ...
    def get_pin_mode(self) -> PinMode: ...
    def get_threshold(self) -> float: ...
    def set_compliance(self, arg0: float) -> None: ...
    def set_mode(self, arg0: PinMode) -> None: ...
    def set_threshold(self, arg0: float) -> None: ...

class PinMode:
    __members__: ClassVar[dict] = ...  # read-only
    BY_HEIGHT: ClassVar[PinMode] = ...
    NONE: ClassVar[PinMode] = ...
    TOP_CORNERS: ClassVar[PinMode] = ...
    __entries: ClassVar[dict] = ...
    def __init__(self, value: int) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __index__(self) -> int: ...
    def __int__(self) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    @property
    def name(self) -> str: ...
    @property
    def value(self) -> int: ...

class PlaneCollider(Collider):
    def __init__(self, origin: numpy.ndarray[numpy.float64[3, 1]], normal: numpy.ndarray[numpy.float64[3, 1]], friction: float) -> None: ...

class Renderer:
    def __init__(self, *args, **kwargs) -> None: ...
    def set_shader_path(self, path: str) -> None: ...

class SceneExporter:
    def __init__(self, *args, **kwargs) -> None: ...
    @staticmethod
    def save_scene(arg0: str, arg1: str, arg2: Solver, arg3: World) -> None: ...

class SceneHeader:
    def __init__(self, *args, **kwargs) -> None: ...
    @property
    def colliders(self) -> list[ColliderInfo]: ...
    @property
    def fabrics(self) -> list[FabricInfo]: ...
    @property
    def name(self) -> str: ...
    @property
    def physics_preset(self) -> str: ...
    @property
    def version(self) -> float: ...

class SceneLoader:
    def __init__(self, *args, **kwargs) -> None: ...
    @staticmethod
    def get_scene_header(arg0: str) -> SceneHeader: ...
    @staticmethod
    def load_scene(arg0: str, arg1: Solver, arg2: World) -> None: ...

class Solver:
    def __init__(self) -> None: ...
    def add_bending_constraint(self, arg0: int, arg1: int, arg2: int, arg3: int, arg4: float, arg5: float) -> None: ...
    def add_distance_constraint(self, arg0: int, arg1: int, arg2: float) -> None: ...
    def add_particle(self, arg0: Particle) -> int: ...
    def add_pin(self, arg0: int, arg1: numpy.ndarray[numpy.float64[3, 1]], arg2: float) -> None: ...
    def add_stitch(self, arg0: int, arg1: int, arg2: float) -> None: ...
    def add_volume_constraint(self, arg0: list[Triangle], arg1: list[Particle], arg2: float) -> float: ...
    def clear(self) -> None: ...
    def get_frame(self) -> int: ...
    def get_iterations(self) -> int: ...
    def get_particles(self) -> list[Particle]: ...
    def get_substeps(self) -> int: ...
    def get_time(self) -> float: ...
    def set_collision_compliance(self, arg0: float) -> None: ...
    def set_iterations(self, arg0: int) -> None: ...
    def set_substeps(self, arg0: int) -> None: ...
    def soft_reset(self) -> None: ...
    def unpin(self, arg0: int) -> None: ...
    def update(self, world: World, delta_time: float) -> None: ...

class SpatialHash:
    def __init__(self, table_size: int, cell_size: float) -> None: ...
    def build(self, particles: list[Particle]) -> None: ...
    def query(self, particles: list[Particle], pos: numpy.ndarray[numpy.float64[3, 1]], radius: float, out_neighbors: list[int]) -> None: ...

class SphereCollider(Collider):
    def __init__(self, center: numpy.ndarray[numpy.float64[3, 1]], radius: float, friction: float) -> None: ...

class StateInfo:
    def __init__(self, *args, **kwargs) -> None: ...
    @property
    def frame(self) -> int: ...
    @property
    def particle_count(self) -> int: ...
    @property
    def timestamp(self) -> float: ...
    @property
    def version(self) -> int: ...

class StateSerializer:
    def __init__(self, *args, **kwargs) -> None: ...
    @staticmethod
    def get_state_info(arg0: str) -> StateInfo: ...
    @staticmethod
    def load(arg0: str, arg1: Solver, arg2: World) -> bool: ...
    @staticmethod
    def save(arg0: str, arg1: Solver, arg2: World) -> bool: ...

class Triangle:
    a: int
    b: int
    c: int
    def __init__(self, a: int, b: int, c: int) -> None: ...

class VolumeConstraint(Constraint):
    def __init__(self, triangles: list[Triangle], particles: list[Particle], compliance: float) -> None: ...
    def get_rest_volume(self) -> float: ...

class World:
    def __init__(self) -> None: ...
    def add_capsule_collider(self, arg0: numpy.ndarray[numpy.float64[3, 1]], arg1: numpy.ndarray[numpy.float64[3, 1]], arg2: float, arg3: float) -> None: ...
    def add_cloth(self, arg0) -> None: ...
    def add_collider(self, arg0: Collider) -> None: ...
    def add_force(self, arg0: Force) -> None: ...
    def add_mesh_collider(self, arg0: str, arg1: float) -> None: ...
    def add_plane_collider(self, arg0: numpy.ndarray[numpy.float64[3, 1]], arg1: numpy.ndarray[numpy.float64[3, 1]], arg2: float) -> None: ...
    def add_sphere_collider(self, arg0: numpy.ndarray[numpy.float64[3, 1]], arg1: float, arg2: float) -> None: ...
    def clear(self) -> None: ...
    def get_air_density(self) -> float: ...
    def get_cloths(self, *args, **kwargs): ...
    def get_colliders(self) -> list[Collider]: ...
    def get_gravity(self) -> numpy.ndarray[numpy.float64[3, 1]]: ...
    def get_thickness(self) -> float: ...
    def get_wind(self) -> numpy.ndarray[numpy.float64[3, 1]]: ...
    def move_collider(self, index: int, new_position: numpy.ndarray[numpy.float64[3, 1]], new_rotation: numpy.ndarray[numpy.float64[4, 1]]) -> None: ...
    def set_air_density(self, arg0: float) -> None: ...
    def set_gravity(self, arg0: numpy.ndarray[numpy.float64[3, 1]]) -> None: ...
    def set_thickness(self, arg0: float) -> None: ...
    def set_wind(self, arg0: numpy.ndarray[numpy.float64[3, 1]]) -> None: ...
