from typing import ClassVar, overload

import numpy

class AeroFace:
    a: int
    b: int
    c: int
    def __init__(self, a: int, b: int, c: int) -> None: ...

class AerodynamicForce(Force):
    def __init__(
        self, faces: list[AeroFace], wind_velocity: numpy.ndarray[numpy.float64[3, 1]], air_density: float
    ) -> None: ...

class AlembicExporter:
    def __init__(self) -> None: ...
    def close(self) -> None: ...
    def open(
        self,
        path: str,
        names: list[str],
        global_positions: numpy.ndarray[numpy.float64],
        global_indices: list,
        particle_indices: list,
    ) -> bool: ...
    def write_frame(self, global_positions: numpy.ndarray[numpy.float64], time: float) -> None: ...

class Application:
    def __init__(self) -> None: ...
    def get_renderer(self) -> Renderer: ...
    def init(self, width: int, height: int, title: str, shader_path: str) -> bool: ...
    def run(self) -> None: ...
    def set_aero_force(self, force: AerodynamicForce) -> None: ...
    def set_cloth(self, cloth: Cloth) -> None: ...
    def set_mesh(self, mesh: ClothMesh) -> None: ...
    def set_solver(self, solver: Solver) -> None: ...
    def set_world(self, world: World) -> None: ...
    def shutdown(self) -> None: ...
    def sync_visual_topology(self) -> None: ...

class AttachmentConstraint(Constraint):
    @overload
    def __init__(
        self, particle_id: int, collider, target_vertex_id: int, compliance: float = ..., rest_length: float = ...
    ) -> None: ...
    @overload
    def __init__(
        self,
        particle_id: int,
        collider,
        local_anchor: numpy.ndarray[numpy.float64[3, 1]],
        compliance: float = ...,
        rest_length: float = ...,
    ) -> None: ...
    def get_particle_id(self) -> int: ...

class BendingConstraint(Constraint):
    def __init__(self, idA: int, idB: int, idC: int, idD: int, restAngle: float, compliance: float) -> None: ...

class CapsuleCollider(Collider):
    def __init__(
        self,
        radius: float,
        start: numpy.ndarray[numpy.float64[3, 1]],
        end: numpy.ndarray[numpy.float64[3, 1]],
        friction: float,
    ) -> None: ...

class Cloth:
    def __init__(self, name: str, material: ClothMaterial) -> None: ...
    def get_aerofaces(self) -> list[AeroFace]: ...
    def get_material(self) -> ClothMaterial: ...
    def get_name(self) -> str: ...
    def get_particle_id(self, row: int, col: int) -> int: ...
    def get_particle_indices(self) -> list[int]: ...
    def get_pin(self) -> Pin: ...
    def get_rest_volume(self) -> float: ...
    def get_triangles(self) -> list[int]: ...
    def get_triangles_native(self) -> list[Triangle]: ...
    def is_closed(self) -> bool: ...
    def set_material(self, material: ClothMaterial) -> None: ...
    def set_pin(self, pin: Pin) -> None: ...
    def set_rest_volume(self, rest_volume: float) -> None: ...

class ClothMaterial:
    bending_compliance: float
    density: float
    shear_compliance: float
    structural_compliance: float
    def __init__(self, density: float, structural: float, shear: float, bending: float) -> None: ...

class ClothMesh:
    def __init__(self) -> None: ...
    def build_from_mesh(
        self,
        positions: list[numpy.ndarray[numpy.float64[3, 1]]],
        indices: list[int],
        out_cloth,
        solver: Solver,
        mesh_path: str,
        translation: numpy.ndarray[numpy.float64[3, 1]] = ...,
        rotation: numpy.ndarray[numpy.float64[4, 1]] = ...,
    ) -> None: ...
    def init_grid(
        self,
        rows: int,
        cols: int,
        spacing: float,
        out_cloth,
        solver: Solver,
        translation: numpy.ndarray[numpy.float64[3, 1]] = ...,
        rotation: numpy.ndarray[numpy.float64[4, 1]] = ...,
    ) -> None: ...

class Collider:
    def __init__(self, *args, **kwargs) -> None: ...
    def get_friction(self) -> float: ...
    def get_name(self) -> str: ...
    def get_position(self) -> numpy.ndarray[numpy.float64[3, 1]]: ...
    def get_rotation(self, *args, **kwargs): ...
    def set_friction(self, friction: float) -> None: ...
    def set_name(self, name: str) -> None: ...

class ColliderInfo:
    def __init__(self, *args, **kwargs) -> None: ...
    @property
    def name(self) -> str: ...
    @property
    def summary(self) -> str: ...
    @property
    def type(self) -> str: ...

class ConfigLoader:
    def __init__(self, *args, **kwargs) -> None: ...
    @staticmethod
    def load_material(filepath: str, material: ClothMaterial) -> None: ...
    @staticmethod
    def load_physics(filepath: str, solver: Solver, world: World) -> None: ...
    @staticmethod
    def save_material(filepath: str, material: ClothMaterial, name: str) -> None: ...
    @staticmethod
    def save_physics(filepath: str, solver: Solver, world: World, name: str) -> None: ...

class Constraint:
    def __init__(self, *args, **kwargs) -> None: ...
    def reset_lambda(self) -> None: ...

class DistanceConstraint(Constraint):
    def __init__(self, idA: int, idB: int, restLength: float, compliance: float) -> None: ...

class FabricInfo:
    def __init__(self, *args, **kwargs) -> None: ...
    @property
    def cols(self) -> int: ...
    @property
    def material(self) -> str: ...
    @property
    def name(self) -> str: ...
    @property
    def pin_mode(self) -> str: ...
    @property
    def rows(self) -> int: ...
    @property
    def source(self) -> str: ...
    @property
    def spacing(self) -> float: ...
    @property
    def type(self) -> str: ...

class Force:
    def __init__(self, *args, **kwargs) -> None: ...

class GravityForce(Force):
    def __init__(self, gravity: numpy.ndarray[numpy.float64[3, 1]]) -> None: ...
    def get_gravity(self) -> numpy.ndarray[numpy.float64[3, 1]]: ...
    def set_gravity(self, gravity: numpy.ndarray[numpy.float64[3, 1]]) -> None: ...

class Logger:
    def __init__(self, *args, **kwargs) -> None: ...
    @staticmethod
    def error(message: str) -> None: ...
    @staticmethod
    def info(message: str) -> None: ...
    @staticmethod
    def warn(message: str) -> None: ...

class MeshCollider(Collider):
    @overload
    def __init__(self, mesh_path: str, friction: float) -> None: ...
    @overload
    def __init__(self, vertices: list[numpy.ndarray[numpy.float64[3, 1]]], triangles, friction: float) -> None: ...
    def get_mesh_path(self) -> str: ...
    def get_world_vertices(self) -> list[numpy.ndarray[numpy.float64[3, 1]]]: ...

class OBJExporter:
    def __init__(self) -> None: ...
    @staticmethod
    def export_obj(filename: str, cloth: Cloth, solver: Solver) -> None: ...

class OBJLoader:
    def __init__(self, *args, **kwargs) -> None: ...
    @staticmethod
    def load(path: str) -> tuple[bool, list[numpy.ndarray[numpy.float64[3, 1]]], list[int]]: ...

class Particle:
    def __init__(self, initial_pos: numpy.ndarray[numpy.float64[3, 1]]) -> None: ...
    def add_force(self, force: numpy.ndarray[numpy.float64[3, 1]]) -> None: ...
    def get_inverse_mass(self) -> float: ...
    def get_old_position(self) -> numpy.ndarray[numpy.float64[3, 1]]: ...
    def get_position(self) -> numpy.ndarray[numpy.float64[3, 1]]: ...
    def get_velocity(self, arg0: float) -> numpy.ndarray[numpy.float64[3, 1]]: ...
    def integrate(self, dt: float) -> None: ...
    def set_inverse_mass(self, inverse_mass: float) -> None: ...
    def set_old_position(self, old_position: numpy.ndarray[numpy.float64[3, 1]]) -> None: ...
    def set_position(self, position: numpy.ndarray[numpy.float64[3, 1]]) -> None: ...

class Pin:
    def __init__(self, pin_mode: PinMode, compliance: float, threshold: float) -> None: ...
    def get_compliance(self) -> float: ...
    def get_pin_mode(self) -> PinMode: ...
    def get_threshold(self) -> float: ...
    def set_compliance(self, compliance: float) -> None: ...
    def set_mode(self, pin_mode: PinMode) -> None: ...
    def set_threshold(self, threshold: float) -> None: ...

class PinMode:
    __members__: ClassVar[dict] = ...  # read-only
    BY_HEIGHT: ClassVar[PinMode] = ...
    NONE: ClassVar[PinMode] = ...
    TOP_CORNERS: ClassVar[PinMode] = ...
    __entries: ClassVar[dict] = ...
    def __init__(self, value: int) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __index__(self) -> int: ...
    def __int__(self) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    @property
    def name(self) -> str: ...
    @property
    def value(self) -> int: ...

class PlaneCollider(Collider):
    def __init__(
        self, origin: numpy.ndarray[numpy.float64[3, 1]], normal: numpy.ndarray[numpy.float64[3, 1]], friction: float
    ) -> None: ...

class Renderer:
    def __init__(self, *args, **kwargs) -> None: ...
    def set_shader_path(self, path: str) -> None: ...

class SceneExporter:
    def __init__(self, *args, **kwargs) -> None: ...
    @staticmethod
    def save_scene(filepath: str, name: str, solver: Solver, world: World) -> None: ...

class SceneHeader:
    def __init__(self, *args, **kwargs) -> None: ...
    @property
    def colliders(self) -> list[ColliderInfo]: ...
    @property
    def fabrics(self) -> list[FabricInfo]: ...
    @property
    def name(self) -> str: ...
    @property
    def physics_preset(self) -> str: ...
    @property
    def version(self) -> float: ...

class SceneLoader:
    def __init__(self, *args, **kwargs) -> None: ...
    @staticmethod
    def get_scene_header(filepath: str) -> SceneHeader: ...
    @staticmethod
    def load_scene(filepath: str, solver: Solver, world: World) -> None: ...

class Solver:
    def __init__(self) -> None: ...
    def add_attach(
        self,
        particle_id: int,
        collider: Collider,
        local_anchor: numpy.ndarray[numpy.float64[3, 1]],
        compliance: float,
        rest_length: float,
    ) -> None: ...
    def add_attachment(
        self,
        particle_id: int,
        collider: Collider,
        target_vertex_id: int,
        compliance: float = ...,
        rest_length: float = ...,
    ) -> None: ...
    def add_attachment_local(
        self,
        particle_id: int,
        collider: Collider,
        local_anchor: numpy.ndarray[numpy.float64[3, 1]],
        compliance: float = ...,
        rest_length: float = ...,
    ) -> None: ...
    def add_bending_constraint(
        self, p1: int, p2: int, p3: int, p4: int, rest_angle: float, compliance: float
    ) -> None: ...
    def add_distance_constraint(self, p1: int, p2: int, compliance: float) -> None: ...
    def add_particle(self, particle: Particle) -> int: ...
    def add_pin(
        self, particle_id: int, target_position: numpy.ndarray[numpy.float64[3, 1]], compliance: float = ...
    ) -> None: ...
    def add_stitch(self, p1: int, p2: int, compliance: float) -> None: ...
    def add_volume_constraint(
        self, triangles: list[Triangle], particles: list[Particle], compliance: float
    ) -> float: ...
    def clear(self) -> None: ...
    def get_frame(self) -> int: ...
    def get_iterations(self) -> int: ...
    def get_particles(self) -> list[Particle]: ...
    def get_substeps(self) -> int: ...
    def get_time(self) -> float: ...
    def remove_attach(self, particle_id: int) -> None: ...
    def remove_attachment(self, particle_id: int) -> None: ...
    def set_collision_compliance(self, compliance: float) -> None: ...
    def set_iterations(self, iterations: int) -> None: ...
    def set_substeps(self, substeps: int) -> None: ...
    def soft_reset(self) -> None: ...
    def unpin(self, particle_id: int) -> None: ...
    def update(self, world: World, delta_time: float) -> None: ...

class SpatialHash:
    def __init__(self, table_size: int, cell_size: float) -> None: ...
    def build(self, particles: list[Particle]) -> None: ...
    def query(
        self,
        particles: list[Particle],
        pos: numpy.ndarray[numpy.float64[3, 1]],
        radius: float,
        out_neighbors: list[int],
    ) -> None: ...

class SphereCollider(Collider):
    def __init__(self, center: numpy.ndarray[numpy.float64[3, 1]], radius: float, friction: float) -> None: ...

class StateInfo:
    def __init__(self, *args, **kwargs) -> None: ...
    @property
    def frame(self) -> int: ...
    @property
    def particle_count(self) -> int: ...
    @property
    def timestamp(self) -> float: ...
    @property
    def version(self) -> int: ...

class StateSerializer:
    def __init__(self, *args, **kwargs) -> None: ...
    @staticmethod
    def get_state_info(path: str) -> StateInfo: ...
    @staticmethod
    def load(path: str, solver: Solver, world: World) -> bool: ...
    @staticmethod
    def save(path: str, solver: Solver, world: World) -> bool: ...

class Triangle:
    a: int
    b: int
    c: int
    def __init__(self, a: int, b: int, c: int) -> None: ...

class VolumeConstraint(Constraint):
    def __init__(self, triangles: list[Triangle], particles: list[Particle], compliance: float) -> None: ...
    def get_rest_volume(self) -> float: ...

class World:
    def __init__(self) -> None: ...
    def add_capsule_collider(
        self,
        start: numpy.ndarray[numpy.float64[3, 1]],
        end: numpy.ndarray[numpy.float64[3, 1]],
        radius: float,
        friction: float,
        name: str,
    ) -> None: ...
    def add_cloth(self, cloth) -> None: ...
    def add_collider(self, collider: Collider) -> None: ...
    def add_force(self, force: Force) -> None: ...
    def add_mesh_collider(self, path: str, friction: float, name: str) -> None: ...
    def add_plane_collider(
        self,
        position: numpy.ndarray[numpy.float64[3, 1]],
        normal: numpy.ndarray[numpy.float64[3, 1]],
        friction: float,
        name: str,
    ) -> None: ...
    def add_sphere_collider(
        self, center: numpy.ndarray[numpy.float64[3, 1]], radius: float, friction: float, name: str
    ) -> None: ...
    def clear(self) -> None: ...
    def get_air_density(self) -> float: ...
    def get_cloths(self, *args, **kwargs): ...
    def get_colliders(self) -> list[Collider]: ...
    def get_gravity(self) -> numpy.ndarray[numpy.float64[3, 1]]: ...
    def get_thickness(self) -> float: ...
    def get_wind(self) -> numpy.ndarray[numpy.float64[3, 1]]: ...
    def move_collider(
        self,
        index: int,
        new_position: numpy.ndarray[numpy.float64[3, 1]],
        new_rotation: numpy.ndarray[numpy.float64[4, 1]],
    ) -> None: ...
    def set_air_density(self, density: float) -> None: ...
    def set_gravity(self, gravity: numpy.ndarray[numpy.float64[3, 1]]) -> None: ...
    def set_thickness(self, thickness: float) -> None: ...
    def set_wind(self, wind: numpy.ndarray[numpy.float64[3, 1]]) -> None: ...
